--
-- PostgreSQL database dump
--

\restrict xV04gQ8VbQMqQlLqu8x7m5jUMbo5p6Z8HzbNYOY55PbbQYRb9pUykFfz3zjarYk

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: boq_boq; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boq_boq (
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(30) NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    is_frozen boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    project_id uuid NOT NULL,
    deleted_at timestamp with time zone,
    ai_confidence_score double precision NOT NULL,
    ai_model character varying(100),
    approved_at timestamp with time zone,
    approved_by_id uuid,
    generation_time double precision,
    rejection_reason text,
    reviewed_at timestamp with time zone,
    reviewed_by_id uuid,
    validation_summary jsonb NOT NULL
);


--
-- Name: boq_boqitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boq_boqitem (
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    item_no character varying(50) NOT NULL,
    description text NOT NULL,
    unit character varying(50) NOT NULL,
    quantity numeric(12,3) NOT NULL,
    rate numeric(12,2) NOT NULL,
    amount numeric(15,2) NOT NULL,
    confidence_score double precision NOT NULL,
    source_reference text,
    created_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    is_ai_generated boolean NOT NULL,
    last_edited_at timestamp with time zone,
    last_edited_by_id uuid,
    section_id uuid NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: boq_boqsection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boq_boqsection (
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    boq_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT boq_boqsection_order_check CHECK (("order" >= 0))
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: documents_uploadeddocument; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents_uploadeddocument (
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    file character varying(100) NOT NULL,
    original_filename character varying(255) NOT NULL,
    extracted_text text,
    status character varying(50) NOT NULL,
    processing_error text,
    uploaded_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL,
    project_id uuid
);


--
-- Name: pricing_rateaudit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pricing_rateaudit (
    id uuid NOT NULL,
    old_rate numeric(14,2),
    new_rate numeric(14,2),
    action character varying(20) NOT NULL,
    source character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id uuid,
    organization_id uuid,
    project_id uuid,
    rate_id uuid NOT NULL
);


--
-- Name: pricing_ratelibrary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pricing_ratelibrary (
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    element character varying(255) NOT NULL,
    description text NOT NULL,
    unit character varying(50) NOT NULL,
    location character varying(100) NOT NULL,
    base_rate numeric(14,2),
    confidence_score double precision NOT NULL,
    source character varying(20) NOT NULL,
    review_status character varying(20) NOT NULL,
    reviewed_at timestamp with time zone,
    is_active boolean NOT NULL,
    organization_id uuid NOT NULL,
    project_id uuid,
    reviewed_by_id uuid
);


--
-- Name: projects_project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects_project (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    status character varying(20) NOT NULL,
    is_frozen boolean NOT NULL,
    created_by_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: users_organization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_organization (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(20) NOT NULL,
    subscription_plan character varying(20) NOT NULL,
    max_users integer NOT NULL,
    max_projects integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT users_organization_max_projects_check CHECK ((max_projects >= 0)),
    CONSTRAINT users_organization_max_users_check CHECK ((max_users >= 0))
);

ALTER TABLE ONLY public.users_organization FORCE ROW LEVEL SECURITY;


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL
);


--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add organization	6	add_organization
22	Can change organization	6	change_organization
23	Can delete organization	6	delete_organization
24	Can view organization	6	view_organization
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add project	8	add_project
30	Can change project	8	change_project
31	Can delete project	8	delete_project
32	Can view project	8	view_project
33	Can add bo q item	9	add_boqitem
34	Can change bo q item	9	change_boqitem
35	Can delete bo q item	9	delete_boqitem
36	Can view bo q item	9	view_boqitem
37	Can add bo q	10	add_boq
38	Can change bo q	10	change_boq
39	Can delete bo q	10	delete_boq
40	Can view bo q	10	view_boq
41	Can add bo q section	11	add_boqsection
42	Can change bo q section	11	change_boqsection
43	Can delete bo q section	11	delete_boqsection
44	Can view bo q section	11	view_boqsection
45	Can add rate library	12	add_ratelibrary
46	Can change rate library	12	change_ratelibrary
47	Can delete rate library	12	delete_ratelibrary
48	Can view rate library	12	view_ratelibrary
49	Can add rate audit	13	add_rateaudit
50	Can change rate audit	13	change_rateaudit
51	Can delete rate audit	13	delete_rateaudit
52	Can view rate audit	13	view_rateaudit
53	Can add uploaded document	14	add_uploadeddocument
54	Can change uploaded document	14	change_uploadeddocument
55	Can delete uploaded document	14	delete_uploadeddocument
56	Can view uploaded document	14	view_uploadeddocument
\.


--
-- Data for Name: boq_boq; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.boq_boq (updated_at, id, name, status, total_amount, is_frozen, created_at, organization_id, project_id, deleted_at, ai_confidence_score, ai_model, approved_at, approved_by_id, generation_time, rejection_reason, reviewed_at, reviewed_by_id, validation_summary) FROM stdin;
\.


--
-- Data for Name: boq_boqitem; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.boq_boqitem (updated_at, id, item_no, description, unit, quantity, rate, amount, confidence_score, source_reference, created_at, organization_id, is_ai_generated, last_edited_at, last_edited_by_id, section_id, deleted_at) FROM stdin;
\.


--
-- Data for Name: boq_boqsection; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.boq_boqsection (updated_at, id, name, "order", created_at, boq_id, organization_id, deleted_at) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	organization
7	users	user
8	projects	project
9	boq	boqitem
10	boq	boq
11	boq	boqsection
12	pricing	ratelibrary
13	pricing	rateaudit
14	documents	uploadeddocument
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-13 11:45:48.85569+01
2	contenttypes	0002_remove_content_type_name	2026-04-13 11:45:48.908114+01
3	auth	0001_initial	2026-04-13 11:45:49.018163+01
4	auth	0002_alter_permission_name_max_length	2026-04-13 11:45:49.033856+01
5	auth	0003_alter_user_email_max_length	2026-04-13 11:45:49.049288+01
6	auth	0004_alter_user_username_opts	2026-04-13 11:45:49.070651+01
7	auth	0005_alter_user_last_login_null	2026-04-13 11:45:49.089781+01
8	auth	0006_require_contenttypes_0002	2026-04-13 11:45:49.123209+01
9	auth	0007_alter_validators_add_error_messages	2026-04-13 11:45:49.14331+01
10	auth	0008_alter_user_username_max_length	2026-04-13 11:45:49.180703+01
11	auth	0009_alter_user_last_name_max_length	2026-04-13 11:45:49.198465+01
12	auth	0010_alter_group_name_max_length	2026-04-13 11:45:49.222987+01
13	auth	0011_update_proxy_permissions	2026-04-13 11:45:49.238965+01
14	auth	0012_alter_user_first_name_max_length	2026-04-13 11:45:49.254199+01
15	users	0001_initial	2026-04-13 11:45:49.398508+01
16	admin	0001_initial	2026-04-13 11:45:49.460036+01
17	admin	0002_logentry_remove_auto_add	2026-04-13 11:45:49.487848+01
18	admin	0003_logentry_add_action_flag_choices	2026-04-13 11:45:49.516965+01
19	sessions	0001_initial	2026-04-13 11:45:49.54285+01
20	projects	0001_initial	2026-04-14 10:16:23.151867+01
21	boq	0001_initial	2026-04-16 11:48:04.510323+01
22	boq	0002_remove_boqitem_boq_boqitem_is_ai_generated_and_more	2026-04-16 12:18:26.268305+01
23	boq	0003_boq_deleted_at_boqitem_deleted_at_and_more	2026-05-20 09:32:11.118496+01
24	projects	0002_project_deleted_at_alter_project_organization	2026-05-20 09:32:11.321632+01
30	pricing	0001_initial	2026-05-25 11:02:35.556297+01
31	documents	0001_initial	2026-05-30 13:17:15.58648+01
32	documents	0002_uploadeddocument_project	2026-06-19 12:02:58.104421+01
33	boq	0004_boq_ai_confidence_score_boq_ai_model_boq_approved_at_and_more	2026-07-08 12:20:11.424868+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: documents_uploadeddocument; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.documents_uploadeddocument (deleted_at, created_at, id, file, original_filename, extracted_text, status, processing_error, uploaded_at, updated_at, organization_id, project_id) FROM stdin;
\N	2026-06-24 12:57:58.90943+01	08224c0a-ac1f-481a-a7f0-a92f9dac8479	uploaded_documents/PROPOSED_LANDSCAPING_EBSB6tu.pdf	PROPOSED LANDSCAPING.pdf	ITEM\nDESCRIPTION\nRATE/SM (N:K)\nPROPOSWED LANDSCAPING\nLOCATION: Abuja, Nigeria\nA\nPreliminaries\n2,500.00\nB\n150mm thick top soil stripping and removal from site\n1,500.00\nC\n250mm imported laterite filling and compaction\n1,650.00\nD\n150mm thick reinforced concrete paving slab including 1-layer\nBRC and associated formwork\n14,200.00\nE\nDrainage\n5,000.00\nF\nKerbs\n1,500.00\nG\nPlumbing installations\n1,000.00\nH\nElectrical installations\n1,500.00\nJ\nHorticulture\n2,500.00\nSub-Total\n31,350.00\nContingency\n1,410.75\nVAT\n2,457.06\nGrand-Total\n35,217.81\n	failed	OpenAI request failed: Error code: 401 - {'error': {'message': 'Incorrect API key provided: Sk-Y2R5a**************************************Gwm8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}	2026-06-24 12:58:01.652073+01	2026-07-15 12:58:07.846965+01	10cde1b2-0cdb-460c-9c9e-47995d4d9845	183020d7-f8d2-4e41-8f08-a2650206daf9
\N	2026-06-01 11:46:08.48325+01	74ed7bd4-9ced-4e62-921e-98de8ad032cb	uploaded_documents/test.pdf	test.pdf	\N	failed	no such file: '/home/vboxcasi/qs_ai_saas/media/uploaded_documents/test.pdf'	2026-06-01 11:46:08.483419+01	2026-06-01 11:49:35.346859+01	10cde1b2-0cdb-460c-9c9e-47995d4d9845	\N
\N	2026-06-21 10:22:19.153914+01	d481f518-6cf6-434d-a100-de3d987358b9	uploaded_documents/sample.pdf	sample.pdf	\N	pending	\N	2026-06-21 10:23:23.620314+01	2026-06-21 10:23:23.620349+01	10cde1b2-0cdb-460c-9c9e-47995d4d9845	183020d7-f8d2-4e41-8f08-a2650206daf9
\N	2026-06-24 12:41:17.28664+01	a4b78a1b-eab2-4f6d-a122-cfd48e389a76	uploaded_documents/PROPOSED_LANDSCAPING.pdf	PROPOSED LANDSCAPING.pdf	\N	pending	\N	2026-06-24 12:41:50.8322+01	2026-06-24 12:41:50.832226+01	10cde1b2-0cdb-460c-9c9e-47995d4d9845	183020d7-f8d2-4e41-8f08-a2650206daf9
\.


--
-- Data for Name: pricing_rateaudit; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pricing_rateaudit (id, old_rate, new_rate, action, source, created_at, created_by_id, organization_id, project_id, rate_id) FROM stdin;
\.


--
-- Data for Name: pricing_ratelibrary; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pricing_ratelibrary (deleted_at, created_at, updated_at, id, element, description, unit, location, base_rate, confidence_score, source, review_status, reviewed_at, is_active, organization_id, project_id, reviewed_by_id) FROM stdin;
\.


--
-- Data for Name: projects_project; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.projects_project (id, created_at, updated_at, name, description, status, is_frozen, created_by_id, organization_id, deleted_at) FROM stdin;
7d7caffa-1bd2-4638-9d43-307877d713c8	2026-05-16 09:19:24.324908+01	2026-05-16 09:19:24.324945+01	QS Test Project	\N	draft	f	05086cf3-4cba-4ab8-aad7-1b94719cbb23	10cde1b2-0cdb-460c-9c9e-47995d4d9845	\N
183020d7-f8d2-4e41-8f08-a2650206daf9	2026-05-16 09:48:30.058093+01	2026-05-16 09:48:30.058336+01	QS Test Project	\N	draft	f	05086cf3-4cba-4ab8-aad7-1b94719cbb23	10cde1b2-0cdb-460c-9c9e-47995d4d9845	\N
58d7e907-5f99-4b1c-a6a3-6be22bf4d230	2026-05-16 09:50:49.859927+01	2026-05-16 09:50:49.860095+01	QS Test Project	\N	draft	f	05086cf3-4cba-4ab8-aad7-1b94719cbb23	10cde1b2-0cdb-460c-9c9e-47995d4d9845	\N
8a37c43b-3d9c-47ee-8e44-ac0273af78dc	2026-05-17 11:18:46.883525+01	2026-05-17 11:18:46.883548+01	QS Test Project	\N	draft	f	05086cf3-4cba-4ab8-aad7-1b94719cbb23	10cde1b2-0cdb-460c-9c9e-47995d4d9845	\N
be482c04-8c30-43f2-b20c-37daec94814b	2026-05-20 09:47:04.36082+01	2026-05-20 09:47:04.360841+01	BoQ Test	\N	draft	f	22f40915-ec38-482a-9ec1-8f886d87a2ec	2b970a93-7428-45b9-9609-29234feaae43	\N
\.


--
-- Data for Name: users_organization; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_organization (id, name, type, subscription_plan, max_users, max_projects, is_active, created_at) FROM stdin;
10cde1b2-0cdb-460c-9c9e-47995d4d9845	Test Org	firm	solo	1	5	t	2026-05-16 09:16:14.609334+01
2b970a93-7428-45b9-9609-29234feaae43	Test Org	firm	solo	1	5	t	2026-05-20 09:45:59.051086+01
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user (password, last_login, is_superuser, id, email, role, is_active, is_staff, created_at, organization_id) FROM stdin;
pbkdf2_sha256$1000000$S8rJ3noyKjviB2zcWQM41P$bgzQVVQtLlJAkljXxw9VdhnVYLHXe/rA6JPTFix66vA=	\N	f	05086cf3-4cba-4ab8-aad7-1b94719cbb23	test@example.com	qs	t	f	2026-05-16 09:18:12.347611+01	10cde1b2-0cdb-460c-9c9e-47995d4d9845
pbkdf2_sha256$1000000$ka26WIzqGaCizlvJOBf2yp$1UZRFyEbzb16sYwsVP6ykYET92CLUHV7JeKo6N0Vdps=	\N	f	22f40915-ec38-482a-9ec1-8f886d87a2ec	test2@example.com	qs	t	f	2026-05-20 09:46:45.613064+01	2b970a93-7428-45b9-9609-29234feaae43
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 33, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: boq_boq boq_boq_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boq
    ADD CONSTRAINT boq_boq_pkey PRIMARY KEY (id);


--
-- Name: boq_boqitem boq_boqitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqitem
    ADD CONSTRAINT boq_boqitem_pkey PRIMARY KEY (id);


--
-- Name: boq_boqsection boq_boqsection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqsection
    ADD CONSTRAINT boq_boqsection_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: documents_uploadeddocument documents_uploadeddocument_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_uploadeddocument
    ADD CONSTRAINT documents_uploadeddocument_pkey PRIMARY KEY (id);


--
-- Name: pricing_rateaudit pricing_rateaudit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_rateaudit
    ADD CONSTRAINT pricing_rateaudit_pkey PRIMARY KEY (id);


--
-- Name: pricing_ratelibrary pricing_ratelibrary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_ratelibrary
    ADD CONSTRAINT pricing_ratelibrary_pkey PRIMARY KEY (id);


--
-- Name: projects_project projects_project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_pkey PRIMARY KEY (id);


--
-- Name: users_organization users_organization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_organization
    ADD CONSTRAINT users_organization_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: boq_boq_approved_by_id_099d60b2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boq_approved_by_id_099d60b2 ON public.boq_boq USING btree (approved_by_id);


--
-- Name: boq_boq_organization_id_87ef1268; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boq_organization_id_87ef1268 ON public.boq_boq USING btree (organization_id);


--
-- Name: boq_boq_project_id_2080e519; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boq_project_id_2080e519 ON public.boq_boq USING btree (project_id);


--
-- Name: boq_boq_reviewed_by_id_6e27fae1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boq_reviewed_by_id_6e27fae1 ON public.boq_boq USING btree (reviewed_by_id);


--
-- Name: boq_boq_status_daefcc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boq_status_daefcc_idx ON public.boq_boq USING btree (status);


--
-- Name: boq_boqitem_last_edited_by_id_0c9e996b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boqitem_last_edited_by_id_0c9e996b ON public.boq_boqitem USING btree (last_edited_by_id);


--
-- Name: boq_boqitem_organization_id_12cf22ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boqitem_organization_id_12cf22ae ON public.boq_boqitem USING btree (organization_id);


--
-- Name: boq_boqitem_section_id_c862776f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boqitem_section_id_c862776f ON public.boq_boqitem USING btree (section_id);


--
-- Name: boq_boqsection_boq_id_c80c4bb2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boqsection_boq_id_c80c4bb2 ON public.boq_boqsection USING btree (boq_id);


--
-- Name: boq_boqsection_organization_id_ba296282; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX boq_boqsection_organization_id_ba296282 ON public.boq_boqsection USING btree (organization_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: documents_uploadeddocument_organization_id_dd4a8c7d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_uploadeddocument_organization_id_dd4a8c7d ON public.documents_uploadeddocument USING btree (organization_id);


--
-- Name: documents_uploadeddocument_project_id_8cafab5f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_uploadeddocument_project_id_8cafab5f ON public.documents_uploadeddocument USING btree (project_id);


--
-- Name: pricing_rat_element_3310da_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rat_element_3310da_idx ON public.pricing_ratelibrary USING btree (element);


--
-- Name: pricing_rat_locatio_a7c94b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rat_locatio_a7c94b_idx ON public.pricing_ratelibrary USING btree (location);


--
-- Name: pricing_rat_organiz_6aa128_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rat_organiz_6aa128_idx ON public.pricing_ratelibrary USING btree (organization_id);


--
-- Name: pricing_rat_project_61da54_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rat_project_61da54_idx ON public.pricing_ratelibrary USING btree (project_id);


--
-- Name: pricing_rateaudit_created_by_id_c9a57200; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rateaudit_created_by_id_c9a57200 ON public.pricing_rateaudit USING btree (created_by_id);


--
-- Name: pricing_rateaudit_organization_id_75453710; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rateaudit_organization_id_75453710 ON public.pricing_rateaudit USING btree (organization_id);


--
-- Name: pricing_rateaudit_project_id_dc63b13b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rateaudit_project_id_dc63b13b ON public.pricing_rateaudit USING btree (project_id);


--
-- Name: pricing_rateaudit_rate_id_be3ba27d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_rateaudit_rate_id_be3ba27d ON public.pricing_rateaudit USING btree (rate_id);


--
-- Name: pricing_ratelibrary_organization_id_f71cd139; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_ratelibrary_organization_id_f71cd139 ON public.pricing_ratelibrary USING btree (organization_id);


--
-- Name: pricing_ratelibrary_project_id_55f9f136; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_ratelibrary_project_id_55f9f136 ON public.pricing_ratelibrary USING btree (project_id);


--
-- Name: pricing_ratelibrary_reviewed_by_id_970613b0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pricing_ratelibrary_reviewed_by_id_970613b0 ON public.pricing_ratelibrary USING btree (reviewed_by_id);


--
-- Name: projects_project_created_by_id_c49d7b6d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX projects_project_created_by_id_c49d7b6d ON public.projects_project USING btree (created_by_id);


--
-- Name: projects_project_organization_id_c93e5ca2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX projects_project_organization_id_c93e5ca2 ON public.projects_project USING btree (organization_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_organization_id_70643736; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_organization_id_70643736 ON public.users_user USING btree (organization_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boq boq_boq_approved_by_id_099d60b2_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boq
    ADD CONSTRAINT boq_boq_approved_by_id_099d60b2_fk_users_user_id FOREIGN KEY (approved_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boq boq_boq_organization_id_87ef1268_fk_users_organization_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boq
    ADD CONSTRAINT boq_boq_organization_id_87ef1268_fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boq boq_boq_project_id_2080e519_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boq
    ADD CONSTRAINT boq_boq_project_id_2080e519_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boq boq_boq_reviewed_by_id_6e27fae1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boq
    ADD CONSTRAINT boq_boq_reviewed_by_id_6e27fae1_fk_users_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boqitem boq_boqitem_last_edited_by_id_0c9e996b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqitem
    ADD CONSTRAINT boq_boqitem_last_edited_by_id_0c9e996b_fk_users_user_id FOREIGN KEY (last_edited_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boqitem boq_boqitem_organization_id_12cf22ae_fk_users_organization_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqitem
    ADD CONSTRAINT boq_boqitem_organization_id_12cf22ae_fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boqitem boq_boqitem_section_id_c862776f_fk_boq_boqsection_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqitem
    ADD CONSTRAINT boq_boqitem_section_id_c862776f_fk_boq_boqsection_id FOREIGN KEY (section_id) REFERENCES public.boq_boqsection(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boqsection boq_boqsection_boq_id_c80c4bb2_fk_boq_boq_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqsection
    ADD CONSTRAINT boq_boqsection_boq_id_c80c4bb2_fk_boq_boq_id FOREIGN KEY (boq_id) REFERENCES public.boq_boq(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: boq_boqsection boq_boqsection_organization_id_ba296282_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boq_boqsection
    ADD CONSTRAINT boq_boqsection_organization_id_ba296282_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_uploadeddocument documents_uploadeddo_organization_id_dd4a8c7d_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_uploadeddocument
    ADD CONSTRAINT documents_uploadeddo_organization_id_dd4a8c7d_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_uploadeddocument documents_uploadeddo_project_id_8cafab5f_fk_projects_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_uploadeddocument
    ADD CONSTRAINT documents_uploadeddo_project_id_8cafab5f_fk_projects_ FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_rateaudit pricing_rateaudit_created_by_id_c9a57200_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_rateaudit
    ADD CONSTRAINT pricing_rateaudit_created_by_id_c9a57200_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_rateaudit pricing_rateaudit_organization_id_75453710_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_rateaudit
    ADD CONSTRAINT pricing_rateaudit_organization_id_75453710_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_rateaudit pricing_rateaudit_project_id_dc63b13b_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_rateaudit
    ADD CONSTRAINT pricing_rateaudit_project_id_dc63b13b_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_rateaudit pricing_rateaudit_rate_id_be3ba27d_fk_pricing_ratelibrary_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_rateaudit
    ADD CONSTRAINT pricing_rateaudit_rate_id_be3ba27d_fk_pricing_ratelibrary_id FOREIGN KEY (rate_id) REFERENCES public.pricing_ratelibrary(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_ratelibrary pricing_ratelibrary_organization_id_f71cd139_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_ratelibrary
    ADD CONSTRAINT pricing_ratelibrary_organization_id_f71cd139_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_ratelibrary pricing_ratelibrary_project_id_55f9f136_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_ratelibrary
    ADD CONSTRAINT pricing_ratelibrary_project_id_55f9f136_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pricing_ratelibrary pricing_ratelibrary_reviewed_by_id_970613b0_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_ratelibrary
    ADD CONSTRAINT pricing_ratelibrary_reviewed_by_id_970613b0_fk_users_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_created_by_id_c49d7b6d_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_created_by_id_c49d7b6d_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_organization_id_c93e5ca2_fk_users_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_organization_id_c93e5ca2_fk_users_org FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_organization_id_70643736_fk_users_organization_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_organization_id_70643736_fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES public.users_organization(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_organization org_isolation_policy; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY org_isolation_policy ON public.users_organization USING (((id)::text = current_setting('app.current_org'::text, true))) WITH CHECK (((current_setting('app.current_org'::text, true) IS NULL) OR ((id)::text = current_setting('app.current_org'::text, true))));


--
-- PostgreSQL database dump complete
--

\unrestrict xV04gQ8VbQMqQlLqu8x7m5jUMbo5p6Z8HzbNYOY55PbbQYRb9pUykFfz3zjarYk

