# Generated by Django 5.2.11 on 2026-05-25 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_deleted_at_alter_project_organization'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLibrary',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=50)),
                ('location', models.CharField(default='Kaduna', max_length=100)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Generated'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_library', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ai_generate', 'AI Generated')], default='created', max_length=20)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='pricing.ratelibrary')),
            ],
        ),
        migrations.AddIndex(
            model_name='ratelibrary',
            index=models.Index(fields=['organization'], name='pricing_rat_organiz_6aa128_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelibrary',
            index=models.Index(fields=['project'], name='pricing_rat_project_61da54_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelibrary',
            index=models.Index(fields=['element'], name='pricing_rat_element_3310da_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelibrary',
            index=models.Index(fields=['location'], name='pricing_rat_locatio_a7c94b_idx'),
        ),
    ]
