# Generated by Django 5.2.11 on 2026-05-21 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0003_boq_deleted_at_boqitem_deleted_at_and_more'),
        ('projects', '0002_project_deleted_at_alter_project_organization'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('source', models.CharField(default='manual', max_length=100)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('original_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('user_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boq.boqitem')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('rate_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.ratelibrary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
