# Generated by Django 5.2.11 on 2026-05-22 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('projects', '0002_project_deleted_at_alter_project_organization'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateaudit',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='boq_item',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='final_rate',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='original_rate',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='rate_library',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rateaudit',
            name='user_override',
        ),
        migrations.RemoveField(
            model_name='ratelibrary',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ratelibrary',
            name='version',
        ),
        migrations.AddField(
            model_name='rateaudit',
            name='action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rateaudit',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rateaudit',
            name='new_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rateaudit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rateaudit',
            name='previous_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rateaudit',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ratelibrary',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ratelibrary',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratelibrary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_library', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='rateaudit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratelibrary',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ratelibrary',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratelibrary',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV Import'), ('ai', 'AI Generated')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ratelibrary',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddIndex(
            model_name='ratelibrary',
            index=models.Index(fields=['organization', 'project', 'location', 'element', 'unit'], name='pricing_rat_organiz_830cc2_idx'),
        ),
    ]
