# Generated by Django 5.2.11 on 2026-05-23 11:33

from django.db import migrations

def fill_actions(apps, schema_editor):
    RateAudit = apps.get_model("pricing", "RateAudit")

    RateAudit.objects.filter(action__isnull=True).update(
        action="created"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_rateaudit_ai_generated_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_actions),
    ]
