# Generated by Django 5.2.11 on 2026-05-23 12:00

from django.db import migrations

def fill_action(apps, schema_editor):
    RateAudit = apps.get_model("pricing", "RateAudit")

    for obj in RateAudit.objects.filter(action__isnull=True):
        obj.action = "created"
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20260523_1133'),
    ]

    operations = [
        migrations.RunPython(fill_action),
    ]
