# Generated by Django 5.2.11 on 2026-05-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20260523_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name="rateaudit",
            old_name="performed_by",
            new_name="created_by",
        ),
    ]
