# Generated by Django 5.2.11 on 2026-04-16 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqitem',
            name='boq',
        ),
        migrations.AddField(
            model_name='boqitem',
            name='is_ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_boq_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BoQSection',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='boq.boq')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='boqitem',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.boqsection'),
            preserve_default=False,
        ),
    ]
