# Generated by Django 5.2.11 on 2026-07-08 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0003_boq_deleted_at_boqitem_deleted_at_and_more'),
        ('projects', '0002_project_deleted_at_alter_project_organization'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='boq',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boq',
            name='generation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_boqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boq',
            name='validation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='boq',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('review_pending', 'Review Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('priced', 'Priced'), ('sealed', 'Sealed')], default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='boq',
            index=models.Index(fields=['status'], name='boq_boq_status_daefcc_idx'),
        ),
    ]
