# Generated by Django 5.2.11 on 2026-06-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0002_project_deleted_at_alter_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
    ]
